global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using System.Collections.ObjectModel;
global using TodoList.Model;
global using TodoList.View;
global using Microsoft.VisualBasic;
global using static System.Runtime.InteropServices.JavaScript.JSType;
